## Welcome to Numpy 

In [1]:
import numpy as np

In [35]:
a = np.array([1,2,3,4,5],dtype = 'i')    #list

In [37]:
print(a)

[1 2 3 4 5]


In [18]:
b = np.array((2,4,6,8,10),dtype = 'f')   #tuple

In [38]:
print(b)

[ 2.  4.  6.  8. 10.]


In [10]:
type(a)

numpy.ndarray

In [11]:
type(b)

numpy.ndarray

In [21]:
b.dtype

dtype('float32')

In [22]:
a.dtype

dtype('int32')

In [27]:
a.ndim

1

In [29]:
c = np.array([[1,2,3],[4,5,6]])

In [30]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
c.ndim

2

In [48]:
c[0,2]

np.int64(3)

In [43]:
a[0]

np.int32(1)

In [72]:
A = np.arange(100)

In [73]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [78]:
B = np.arange(20,100,3)   #for i in range(20,100,3) range(start,end,jumps)
B

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [79]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [80]:
print(range(10))

range(0, 10)


In [81]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
